name: seeip_client
version: 0.1.3
description: A library that makes it easy to fetch data from SeeIP - A simple IP address API.
homepage: https://madaboutbrighton.net/projects/seeip-client
repository: https://github.com/madaboutbrighton/seeip_client
issue_tracker: https://github.com/madaboutbrighton/seeip_client/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  mockito: ^5.0.10
  pedantic: ^1.11.0
  test: ^1.17.5
  build_runner: ^2.0.0
